name: AZ test

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs: 
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: 'Run az commands'
        run: |
          az account show
          az group list

      - name: 'AZ CLI Action'
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az account show
            secret_1=$(az keyvault secret show --name "special-secret" --vault-name "secret-stuff" --query "value")
            echo "secret_1=$(secret_1)" >> $GITHUB_ENV
        
      - name: show secret
        run: |
          echo "secret_1=$(secret_1)"


  build-and-deploy-qa:
    runs-on: ubuntu-latest
    needs: build-and-deploy-dev
    environment: qa
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: 'Run az commands'
        run: |
          az account show
          az group list        
