name: AZ test

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs: 
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    
      - name: 'get deets'
        run: |
          echo "PWD: ${PWD}"
          echo "ls -halt: $(ls -halt)"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          
          cd ~
          echo "PWD: ${PWD}"
          echo "ls -halt: $(ls -halt)"
  
      - name: 'Run az commands'
        run: |
          az account show
          az group list

      - name: Try my azure action
        id: test
        uses: jcantosz/azure-keyvault-action@015089ac9903d0c16fde9741a70e7361b8beb621
        with:
          vaultName: 'secret-stuff'
          objectType: 'secret'
          objectKeys: 'special-secret,cool-secret,-1,'
          outputEnvs: 'true'
          outputOutputs: 'true'

      - name: show secrets
        run: |
          echo "special_secret=${special_secret}"
          echo "cool_secret=${cool_secret}"
          echo "_1=${_1}"
          echo "steps.test.outputs.special_secret=${{ steps.test.outputs.special_secret }}"
          echo "steps.test.outputs.cool_secret=${{ steps.test.outputs.cool_secret }}"
          echo "steps.test.outputs._1=${{ steps.test.outputs._1 }}"

      - name: 'AZ CLI Action'
        id: az-secrets
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az account show
            secret_1=$(az keyvault secret show --name "special-secret" --vault-name "secret-stuff" --query "value")
            echo "::add-mask::${secret_1}"
            echo "secret_1=${secret_1}" >> $GITHUB_ENV


            secret_2=$(az keyvault secret show --name "cool-secret" --vault-name "secret-stuff" --query "value")
            echo "secret_2=${secret_2}"
            echo "secret_1=${secret_1}"
            
            #echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT 
            echo "::set-output name=OTHER_COLOR::purple"
#            echo "::add-mask::${secret_2}"
#            echo "secret_2=${secret_2}" >> $GITHUB_OUTPUT

        
      - name: show secret
        run: |
          echo "secret_1=${secret_1}"

      - name: show secret output
        run: |
          echo "secret_2=${{ steps.az-secrets.outputs.SELECTED_COLOR }}""

  build-and-deploy-qa:
    runs-on: ubuntu-latest
    needs: build-and-deploy-dev
    environment: qa
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: 'Run az commands'
        run: |
          az account show
          az group list        
