name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  

jobs:
  build:

    runs-on: windows-2019
    # https://stackoverflow.com/questions/64295288/could-not-run-the-generateresource-task-because-msbuild-could-not-create-or-co
    env:
        DISABLEOUTOFPROCTASKHOST: 1

    steps:
    - uses: actions/checkout@v3
#    - name: Setup .NET
#      uses: actions/setup-dotnet@v3
#      with:
#        dotnet-version: 4.0.x
    - uses: actions/cache@v3
      with:
        path: |
          ./packages
          !./packages/unwanted
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Restore dependencies
      run: |
        nuget restore
        dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Debug
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Debug

    - uses: actions/upload-artifact@v3
      with:
        name: API
        retention-days: 5
        path: OWINTest.API\bin\Debug\OWINTest.API.dll

    - uses: actions/upload-artifact@v3
      with:
        name: Service
        retention-days: 5
        path: OWINTest.Service\bin\Debug\OWINTest.Service.exe