# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: git-version

on:
  push:

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Install GitVersion
      uses: GitTools/actions@v0.9.15
      with:
        versionSpec: '5.x'
    - name: Determine Version
      uses: GitTools/actions@v0.9.15
    - name: test
      run: |
        env
