name: .NET Release

on:
  release:
    types: [published]
  workflow_dispatch:
  

jobs:
  build:

    runs-on: windows-2019
    # https://stackoverflow.com/questions/64295288/could-not-run-the-generateresource-task-because-msbuild-could-not-create-or-co
    env:
        DISABLEOUTOFPROCTASKHOST: 1
        CONFIGURATION: 'Release'

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ./packages
          !./packages/unwanted
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: |
        nuget restore
        dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration $env:CONFIGURATION
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration $env:CONFIGURATION

    - uses: actions/upload-artifact@v3
      with:
        name: API
        retention-days: 5
        path: OWINTest.API\bin\${{ env.CONFIGURATION }}\OWINTest.API.dll

    - uses: actions/upload-artifact@v3
      with:
        name: Service
        retention-days: 5
        path: OWINTest.Service\bin\${{ env.CONFIGURATION }}\OWINTest.Service.exe

    - name: create release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload $env:GITHUB_REF_NAME OWINTest.Service\bin\$env:CONFIGURATION\OWINTest.Service.exe OWINTest.API\bin\$env:CONFIGURATION\OWINTest.API.dll

    - name: create release 2
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload  OWINTest.API\bin\
